name: llama-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.24.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_core=5.7.2=py310hff52083_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.2=0
  - libnvfatbin=12.6.68=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.14=h955ad1f_1
  - python_abi=3.10=2_cp310
  - pytorch=2.4.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.0.0=py310
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.1.0
    - accelerate==0.34.2
    - adapters==1.0.0
    - aiofiles==23.2.1
    - aiohttp==3.9.5
    - aiohttp-cors==0.7.0
    - aiosignal==1.3.1
    - altair==5.3.0
    - annotated-types==0.7.0
    - anyio==4.4.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.2.0
    - auto-gptq==0.4.2+cu118
    - babel==2.16.0
    - base58==2.1.1
    - beautifulsoup4==4.12.3
    - bitsandbytes==0.43.3
    - black==21.12b0
    - bleach==6.1.0
    - blessed==1.20.0
    - blinker==1.8.2
    - boto3==1.34.115
    - botocore==1.34.115
    - brotli==1.1.0
    - cachetools==5.5.0
    - certifi==2024.8.30
    - cffi==1.17.1
    - chardet==5.2.0
    - chex==0.1.88
    - clarabel==0.9.0
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.29.3
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - colorful==0.5.6
    - comm==0.2.2
    - contourpy==1.2.1
    - croniter==1.3.15
    - cvxpy==1.5.3
    - cycler==0.12.1
    - dataproperty==1.0.1
    - datasets==3.0.0
    - dateutils==0.6.12
    - debugpy==1.6.7
    - deepdiff==7.0.1
    - deepspeed==0.10.3
    - defusedxml==0.7.1
    - dill==0.3.8
    - diskcache==5.6.3
    - distlib==0.3.8
    - distro==1.9.0
    - dm-clrs==2.0.1
    - dm-haiku==0.0.13
    - dnspython==2.6.1
    - docker-pycreds==0.4.0
    - easydict==1.13
    - ecos==2.0.14
    - editor==1.6.6
    - einops==0.8.0
    - email-validator==2.1.1
    - etils==1.11.0
    - evaluate==0.4.3
    - exceptiongroup==1.2.1
    - fastapi==0.111.0
    - fastapi-cli==0.0.4
    - fastjsonschema==2.20.0
    - ffmpy==0.3.2
    - filelock==3.13.1
    - fire==0.6.0
    - flake8==7.1.1
    - flash-attn==2.5.9.post1
    - flatbuffers==24.12.23
    - fonttools==4.52.1
    - fqdn==1.5.1
    - frozenlist==1.4.1
    - fschat==0.2.36
    - fsspec==2023.12.2
    - gast==0.6.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gmpy2==2.1.2
    - google-api-core==2.19.2
    - google-auth==2.34.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.65.0
    - gradio==4.31.5
    - gradio-client==0.16.4
    - grpcio==1.66.1
    - gurobipy==11.0.3
    - h11==0.14.0
    - h5py==3.12.1
    - hjson==3.1.0
    - httpcore==1.0.5
    - httptools==0.6.1
    - httpx==0.27.0
    - huggingface-hub==0.25.0
    - humanfriendly==10.0
    - idna==3.7
    - importlib-resources==6.4.0
    - inflate64==1.0.0
    - iniconfig==2.0.0
    - inquirer==3.2.4
    - inquirerpy==0.3.4
    - interegular==0.3.3
    - ipykernel==6.14.0
    - ipywidgets==8.1.5
    - isoduration==20.11.0
    - isort==5.8.0
    - itsdangerous==2.2.0
    - jax==0.4.38
    - jaxlib==0.4.38
    - jaxtyping==0.2.34
    - jinja2==3.1.4
    - jmespath==1.0.1
    - jmp==0.0.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonlines==4.0.0
    - jsonpointer==3.0.0
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.13
    - keras==3.7.0
    - kiwisolver==1.4.5
    - lark==1.1.9
    - latex2mathml==3.77.0
    - libclang==18.1.1
    - lightning==2.2.5
    - lightning-cloud==0.5.69
    - lightning-utilities==0.11.2
    - line-profiler==4.1.3
    - linkify-it-py==2.0.3
    - llama-recipes==0.0.2
    - llvmlite==0.42.0
    - lm-eval==0.4.2
    - lm-format-enforcer==0.10.1
    - loguru==0.7.3
    - loralib==0.1.2
    - lxml==5.2.2
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markdown2==2.5.0
    - markupsafe==2.1.3
    - matplotlib==3.9.2
    - mbstrdecoder==1.1.3
    - mccabe==0.7.0
    - mdit-py-plugins==0.4.2
    - mdurl==0.1.2
    - memray==1.14.0
    - mistune==3.0.2
    - mkl-fft==1.3.10
    - mkl-random==1.2.7
    - mkl-service==2.4.0
    - ml-collections==1.0.0
    - ml-dtypes==0.4.1
    - more-itertools==10.2.0
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multidict==6.0.5
    - multiprocess==0.70.16
    - multivolumefile==0.2.3
    - mypy==1.11.2
    - mypy-extensions==1.0.0
    - namex==0.0.8
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - networkx==3.3
    - nh3==0.2.18
    - ninja==1.11.1.1
    - nltk==3.8.1
    - notebook-shim==0.2.4
    - numba==0.59.1
    - numexpr==2.10.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.555.43
    - nvidia-ml-py3==7.352.0
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - openai==1.30.3
    - opencensus==0.11.4
    - opencensus-context==0.1.3
    - opt-einsum==3.4.0
    - optax==0.2.4
    - optimum==1.22.0
    - optree==0.12.1
    - ordered-set==4.1.0
    - orjson==3.10.3
    - osqp==0.6.7.post1
    - outlines==0.0.34
    - overrides==7.7.0
    - packaging==22.0
    - pandas==2.2.2
    - pandocfilters==1.5.1
    - pathspec==0.12.1
    - pathvalidate==3.2.0
    - peft==0.5.0
    - pfzy==0.3.4
    - pillow==10.4.0
    - pip==24.2
    - plotly==5.24.1
    - pluggy==1.5.0
    - portalocker==2.8.2
    - prettytable==3.11.0
    - prometheus-client==0.20.0
    - prometheus-fastapi-instrumentator==7.0.0
    - promise==2.3
    - prompt-toolkit==3.0.43
    - proto-plus==1.24.0
    - protobuf==3.20.3
    - psutil==5.9.8
    - ptflops==0.7.3
    - py-cpuinfo==9.0.0
    - py-spy==0.3.14
    - py7zr==0.21.0
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybcj==1.0.2
    - pybind11==2.12.0
    - pycodestyle==2.12.1
    - pycparser==2.22
    - pycryptodomex==3.20.0
    - pydantic==2.7.3
    - pydantic-core==2.18.4
    - pydeck==0.9.1
    - pydub==0.25.1
    - pyflakes==3.2.0
    - pyg-lib==0.4.0+pt24cu124
    - pyjwt==2.8.0
    - pynvml==11.5.0
    - pyparsing==3.1.2
    - pyppmd==1.1.0
    - pysocks==1.7.1
    - pytablewriter==1.2.0
    - pytest==8.3.3
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - python-multipart==0.0.9
    - pytorch-lightning==2.2.5
    - pytorch-quantization==2.1.3
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - pyzstd==0.16.0
    - qdldl==0.1.7.post4
    - ray==2.36.0
    - readchar==4.1.0
    - referencing==0.35.1
    - regex==2024.5.15
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.7.1
    - rouge==1.0.1
    - rouge-score==0.1.2
    - rpds-py==0.18.1
    - rsa==4.9
    - ruff==0.4.5
    - runs==1.2.2
    - s3transfer==0.10.1
    - sacrebleu==2.4.2
    - safetensors==0.4.3
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - scs==3.2.7
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - send2trash==1.8.3
    - sentencepiece==0.2.0
    - sentry-sdk==2.14.0
    - setproctitle==1.3.3
    - setuptools==75.1.0
    - shellingham==1.5.4
    - shortuuid==1.0.13
    - smart-open==7.0.4
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.5
    - sphinx-glpi-theme==0.6
    - sqlitedict==2.1.0
    - stack-data==0.6.3
    - starlette==0.37.2
    - starsessions==1.3.0
    - streamlit==0.82.0
    - svgwrite==1.4.3
    - sympy==1.13.2
    - tabledata==1.3.3
    - tabulate==0.9.0
    - tcolorpy==0.1.6
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tensorflow==2.18.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-metadata==1.16.1
    - termcolor==2.4.0
    - terminado==0.18.1
    - texttable==1.7.0
    - textual==0.79.1
    - tfds-nightly==4.5.2.dev202204190046
    - threadpoolctl==3.5.0
    - tiktoken==0.7.0
    - tinycss2==1.3.0
    - tokenize-rt==5.2.0
    - tokenizers==0.19.1
    - toml==0.10.2
    - tomli==1.2.3
    - tomlkit==0.12.0
    - toolz==0.12.1
    - torch==2.4.1
    - torch-cluster==1.6.3+pt24cu124
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2+pt24cu124
    - torch-sparse==0.6.18+pt24cu124
    - torch-spline-conv==1.2.2+pt24cu124
    - torchaudio==2.4.1
    - torchmetrics==1.4.0.post0
    - torchvision==0.19.1
    - tornado==6.4.1
    - tqdm==4.66.4
    - tqdm-multiprocess==0.0.11
    - transformers==4.43.4
    - triton==3.0.0
    - typeguard==2.13.3
    - typepy==1.3.2
    - typer==0.12.3
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.8.0
    - tzdata==2024.1
    - tzlocal==5.2
    - uc-micro-py==1.0.3
    - ujson==5.10.0
    - uri-template==1.3.0
    - urllib3==2.2.2
    - uvicorn==0.29.0
    - uvloop==0.19.0
    - validators==0.34.0
    - virtualenv==20.26.5
    - vllm==0.4.3
    - vllm-flash-attn==2.5.8.post2
    - wandb==0.18.1
    - watchdog==5.0.2
    - watchfiles==0.21.0
    - wavedrom==2.0.3.post3
    - webcolors==24.8.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - websockets==11.0.3
    - werkzeug==3.1.3
    - wheel==0.44.0
    - widgetsnbextension==4.0.13
    - word2number==1.1
    - wrapt==1.16.0
    - xformers==0.0.26.post1
    - xmod==1.8.1
    - xxhash==3.4.1
    - yacs==0.1.8
    - yarl==1.9.4
    - zstandard==0.22.0
prefix: /home/ldy/miniconda3/envs/llama-env
